"""
Webhook event models - universal format for all DevOps tools.

All webhook events (GitHub, Jenkins, Terraform, Prometheus) normalize
to WebhookEvent format for consistent processing through CodeUChain.
"""

from typing import TypedDict, Any, Optional
from datetime import datetime


class WebhookEvent(TypedDict):
    """
    Universal webhook event format.
    
    All tools normalize their payloads to this format before processing.
    This allows a single chain to handle events from any source.
    """
    event_id: str              # UUID, generated by adapter
    tool: str                  # "github", "jenkins", "terraform", "prometheus"
    event_type: str            # "push", "build_completed", "plan", "alert_fired"
    timestamp: datetime        # When event occurred (in tool's timezone)
    source_url: str            # Link to event in original tool (for UI clickthrough)
    metadata: dict             # Tool-specific fields (repo, branch, job_name, etc.)
    payload: dict              # Original vendor payload (for debugging, audit trail)


class PushEvent(TypedDict):
    """GitHub push or generic Git push event"""
    repository: str            # "org/repo" or full URL
    branch: str                # "main", "develop", "refs/heads/feature-x"
    commit_sha: str            # Full commit hash
    commit_message: str        # Commit message
    author: str                # Committer name
    timestamp: str             # ISO format timestamp
    source_url: str            # Link to commit in tool


class BuildCompletedEvent(TypedDict):
    """Jenkins, CircleCI, GitHub Actions build completion"""
    job_name: str              # Job/workflow name
    build_number: int          # Build ID or run number
    status: str                # "SUCCESS", "FAILURE", "UNSTABLE", "PASSED", "FAILED"
    duration_seconds: int      # Build duration
    logs_url: str              # Link to logs in tool
    branch: Optional[str]      # Branch that was built
    commit_sha: Optional[str]  # Commit that triggered build


class PlanEvent(TypedDict):
    """Terraform Cloud plan event"""
    workspace: str             # Terraform workspace name
    resources_added: int       # Count of resources to add
    resources_changed: int     # Count of resources to modify
    resources_destroyed: int   # Count of resources to delete
    plan_url: str              # Link to plan in Terraform Cloud


class AlertEvent(TypedDict):
    """Prometheus AlertManager alert"""
    alert_name: str            # Alert rule name (e.g., "HighMemoryUsage")
    severity: str              # "critical", "warning", "info"
    status: str                # "firing", "resolved"
    labels: dict               # Alert labels (pod, namespace, etc.)
    annotations: dict          # Alert annotations (description, runbook, etc.)
    timestamp: str             # When alert was triggered
